inputs:
  name:
    description: 'Setup repository and caching'
    default: 'Setup'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git fetch origin develop

    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      env:
        HUSKY_SKIP_INSTALL: 'true'
      run: npm install -- --frozen-lockfile
