# A basic redirects rule

[functions]
  directory = "dist/hub-movies/server"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "dist/hub-movies/server/main"
  status = 200

[dev]
 functionsPort = 2400
