# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add LHCI Server Link

on:
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:

      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '.+'
          # http://localhost:9001/app/projects/angular-movies-perf/compare/163c990e52fe
          body-template: "[LHCI Server](http://localhost:9001/app/projects/)"
          body-update-action: 'suffix'
