# https://github.com/GoogleChrome/lighthouse-ci

name: Lighthouse CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: [ "Hub Movies - Build & Test" ]
    types:
      - completed
jobs:
  lighthouseci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin master

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm

      - name: Run lighthouse ci report
        run: npm run lhci -- autorun

      - name: Archive lighthouse ci artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lhci--hub-movies
          path: |
            dist/hub-movies
